# Generated by Django 4.1.4 on 2022-12-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
